### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by rashevskyv** [ihaveamac/custom-install#1]
1. The program does not check if there is enough space on the memory card for installation
2. If you run the program, and after the end of its work, do not start the installer on the console, but run the program again, then `cifinal.bin` on the memory card will contain data only from the last launch of `custom-install.py`. That is, when the installer is launched on thу console, only the game (s) from the last launch of the script on the PC will be installed. However, games converted by previous launches will not be installed, but they will take up space on the SD.
3. Make convercion proccess on PC. It will be faster and will not overload the memory card. After conversion is complete you can move files to SD
4. Check for `custom-install-finalize.3dsx` on the memory card. If the program is not there, copy it 
5. When I try to give as an argument links for to many local files located in another directory, I get an error. Double slashes is generating by CMD by some reason
https://pastebin.com/Pu4798Ey

You can solve the problem as follows:
a) Delete `cifinal.bin` after each launch of the installer on the console
b) When running the script on the PC, check for the presence of `cifinal.bin`. If there is a file, add information from the last script run on the PC to it; if not, create a new file

I apologize for the probably crooked English.

**Comment by ihaveamac** [comment]
> The program does not check if there is enough space on the memory card for installation

Not yet, I need to find the best cross-platform way to figure this out based on the destination path.

> If you run the program, and after the end of its work, do not start the installer on the console, but run the program again, then `cifinal.bin` on the memory card will contain data only from the last launch of `custom-install.py`. That is, when the installer is launched on thу console, only the game (s) from the last launch of the script on the PC will be installed. However, games converted by previous launches will not be installed, but they will take up space on the SD.

Updating `cifinish.bin` in-place will be coming soon.

> Make convercion proccess on PC. It will be faster and will not overload the memory card. After conversion is complete you can move files to SD

Do you mean converting cci/".3ds" files? Maybe, after other important features are added.

> Check for `custom-install-finalize.3dsx` on the memory card. If the program is not there, copy it

Good idea, though it probably won't copy the file, but instead print a message at the end.

> When I try to give as an argument links for to many local files located in another directory, I get an error. Double slashes is generating by CMD by some reason
https://pastebin.com/Pu4798Ey

This is because all the files are surrounded by a single set of quotes, so it's all being passed as a single argument, not one argument per file. Remove the quotes or put them around each file path that has spaces in it.

**Comment by ihaveamac** [comment]
99556990457ded3d9f2f4b3522715c4032ce2fbc 2f0fc5d177d2423af5579b7b86442a3b56cc025f cifinish.bin is updated in-place and removed by custom-install-finalize

**Comment by ihaveamac** [comment]
19045d8b87ae0b5e4c3c91a925f64f161c7c6e87 3dsx is copied to the SD card if it exists next to the script. This does not check if it already exists in case it's an older version.

**Comment by ihaveamac** [comment]
Some of these will be moved to their own issues.
