### ISSUE TITLE
i dont know that i have done

### ISSUE THREAD

**Issue by AHRI0048** [ihaveamac/custom-install#12]
i just want to install a game use this but why my pc telling me

 PS D:\custom-install-master> py -3 custom-install.py -b boot9.bin -m movable.sed --sd F:\custom-install-master\file.cia
 py : usage: custom-install.py [-h] -m MOVABLE [-b BOOT9] [--sd SD]
 At line:1 char:1
 + py -3 custom-install.py -b boot9.bin -m movable.sed --sd F:\custom-in ...
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (usage: custom-i...OOT9] [--sd SD]:String) [], RemoteException
     + FullyQualifiedErrorId : NativeCommandError
  
                          [--skip-contents]
                          cia [cia ...]
 custom-install.py: error: the following arguments are required: cia 

its i am wrong with this?

**Comment by ihaveamac** [comment]
You're providing the cia as an argument to --sd. What you should be doing is provide a drive letter, and then the cia file.

Example (assuming F: is the drive letter for the SD card, change it if it's not): `--sd F: F:\custom-install-master\file.cia`

**Comment by AHRI0048** [comment]
> You're providing the cia as an argument to --sd. What you should be doing is provide a drive letter, and then the cia file.
> 
> Example (assuming F: is the drive letter for the SD card, change it if it's not): `--sd F: F:\custom-install-master\file.cia`

I already try that i its say wrong argument
Is it different from the new and old version of python? The code

**Comment by ihaveamac** [comment]
I don't think I understand what you're saying. Please post the full error after you give two different arguments, one for --sd and one that is the cia.

**Comment by AHRI0048** [comment]
Ok later i will try it again
