### ISSUE TITLE
Host IO error

### ISSUE THREAD

**Issue by BaamAlex** [ihaveamac/custom-install#17]
![1578068462016](https://user-images.githubusercontent.com/41616471/78997054-2b251880-7b46-11ea-8f25-dfe9956dbd50.png)
I get this error after the installation process. I tried already reinstalling the games. But nothing is changed then. Where is the problem? All files are correctly placed.

**Comment by ihaveamac** [comment]
It looks like it couldn't find title.db. If there are no titles already installed, one easy way you could do this is to install something small with FBI first.

**Comment by ihaveamac** [comment]
I heard just opening FBI should be good enough.

**Comment by BaamAlex** [comment]
I will try that definitely. I appreciate your help. I report later.

**Comment by BaamAlex** [comment]
> I heard just opening FBI should be good enough.

I installed fbi and a few other homebrews. And now it worked perfectly fine. Thanks for your help.

**Comment by ihaveamac** [comment]
I'll be sure to add a check for title.db.
