### ISSUE TITLE
ExeFS reader assumed wrong implementation?

### ISSUE THREAD

**Issue by Originalimoc** [ihaveamac/custom-install#18]
I get some CIAs with exceptions that don't make sense given 3dbrew and my removal/bypass of that rasing followed by get not a multiple of 0x200 error too.

``Traceback (most recent call last):
  File "custom-install.py", line 92, in <module>
    cia = CIAReader(c)
  File "C:\Users\imoc\Desktop\TargetCIAs\pyctr\types\cia.py", line 174, in __init__
    self.contents[record.cindex] = NCCHReader(content_fp, case_insensitive=case_insensitive,
  File "C:\Users\imoc\Desktop\TargetCIAs\pyctr\types\ncch.py", line 248, in __init__
    self.load_sections()
  File "C:\Users\imoc\Desktop\TargetCIAs\pyctr\types\ncch.py", line 286, in load_sections
    self.exefs = ExeFSReader(exefs_fp, _load_icon=False)
  File "C:\Users\imoc\Desktop\TargetCIAs\pyctr\types\exefs.py", line 211, in __init__
    raise ExeFSNameError(entry_raw[0:8])
pyctr.types.exefs.ExeFSNameError: could not decode from ascii: b'\xe8j\xaf\x89\xed\xc5\x9c='``
and
``.... could not decode from ascii: b'2\x98s\xc6\x83Q`\xc0' ......``

They can be installed by FBI though.

**Comment by ZeroSkill1** [comment]
I've got the same issue here.

**Comment by ihaveamac** [comment]
What kind of title are you trying to install?

**Comment by ZeroSkill1** [comment]
Just a normal game (Pokemon Ultra Moon), but it seems like my file is zerokey encrypted, I'll encrypt it using GM9 and try again. It seems like it does not like zerokey encrypted files. I originally converted the game from .3ds to .cia using 3dsconv, which told me it was zerokey

**Comment by ihaveamac** [comment]
Weird, I thought I had zerokey support. I'll look into it.

**Comment by ZeroSkill1** [comment]
Yeah, I encrypted it using GM9 and now it's installing as it would normally.

**Comment by ihaveamac** [comment]
I forgot to support zerokey files in pyctr. I'll get on that eventually...

**Comment by ihaveamac** [comment]
pyctr now supports this: https://github.com/ihaveamac/pyctr/commit/1bf6355cdc236b6f0f0068bb995e41fa8be2ce15 and https://github.com/ihaveamac/pyctr/commit/f04bc5a09b448605b7c69a7cffec54540b80c0d8
As soon as a new release is made and ninfs is updated for it, this issue will be closed.

**Comment by ihaveamac** [comment]
Should be supported with https://github.com/ihaveamac/custom-install/commit/13f706a0dcb28c60687bccee93a4ee14b20144fd now, make sure to update pyctr (download the repo and re-do "Install the packages").
