### ISSUE TITLE
Signature Mismatch Error

### ISSUE THREAD

**Issue by REY3DS** [ihaveamac/custom-install#19]
Please help I have an error

![help](https://user-images.githubusercontent.com/65413634/82074913-bceeeb00-96db-11ea-9e66-2d18afc15f73.PNG)

**Comment by ihaveamac** [comment]
title.db might be corrupt. Are you able to see any installed titles on the 3DS?

**Comment by REY3DS** [comment]
Yes I can view my games in my 3ds

**Comment by REY3DS** [comment]
And the fbi and other aplications

**Comment by REY3DS** [comment]
I have another error it says the rute is not find but says a id0 different to my id0

Sorry for the bad english im spanish

**Comment by ihaveamac** [comment]
That means a different ID0 is being used than the one the 3DS is using right now, so try dumping that again. Copy it from SYSNAND CTRNAND -> private -> movable.sed in GodMode9.

**Comment by REY3DS** [comment]
ok thanks

**Comment by REY3DS** [comment]
im gona try it

**Comment by REY3DS** [comment]
when I launch the custom install finalize it says cifinish magic not found in cifinish.bin

**Comment by ihaveamac** [comment]
Where did you get custom-install-finalize from? If the release doesn't work, try this one, from module-new-gui.
[custom-install-finalize.3dsx.zip](https://github.com/ihaveamac/custom-install/files/4643921/custom-install-finalize.3dsx.zip)

**Comment by REY3DS** [comment]
ok im gona try it

**Comment by REY3DS** [comment]
I use the release custom install finalize

**Comment by REY3DS** [comment]
with the release it doesn t worked

**Comment by REY3DS** [comment]
it doesnt work with the new gui

**Comment by REY3DS** [comment]
im sad :,c

**Comment by ihaveamac** [comment]
I don't have a good solution at the moment, I'll eventually get around to fixing certain problems with this program. Just kinda busy with other things right now.

**Comment by REY3DS** [comment]
ok sorry for wasting your time

**Comment by REY3DS** [comment]
now my title.db is corrupted how i can fix it ?

**Comment by ihaveamac** [comment]
You'll need to use rebuild-title-database to recreate it. https://git.ianburgwin.net/ianburgwin/rebuild-title-database

**Comment by ihaveamac** [comment]
There is also a new release that will work with any cifinish version. https://github.com/ihaveamac/custom-install/releases/tag/finalize-1.3

**Comment by REY3DS** [comment]
thanks
