### ISSUE TITLE
Can't find save3ds_fuse on msys2

### ISSUE THREAD

**Issue by aetha** [ihaveamac/custom-install#2]
This is just a minor issue. custom-install crashes running under msys2:
```
Traceback (most recent call last):
  File "custom-install.py", line 318, in <module>
    subprocess.run(save3ds_fuse_common_args + ['-x'])
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bin/msys/save3ds_fuse': 'bin/msys/save3ds_fuse'
```
Copying the bin/win32 directory to bin/msys fixes the issue.

**Comment by evertonstz** [comment]
What's the system you're running this on? It seems python is having some problems in detecting your system as win32 and is instead detecting it as msys. Could be as simple as adding a if statement here https://github.com/ihaveamac/custom-install/blob/00c0e81c26d6d0558a320fb05f162df511c3c8a5/custom-install.py#L304 but might be wort investigating a little further.

**Comment by ihaveamac** [comment]
I'll probably make it redirect to win32 if msys is detected.
