### ISSUE TITLE
cia won't install not sure of the issue?

### ISSUE THREAD

**Issue by zayn5498** [ihaveamac/custom-install#25]
Writing /title/00040000/0f702f00/content/cmd/00000001.cmd

Traceback (most recent call last):

  File "C:\Users\zayn5\Downloads\custom-install-module-new-gui\custominstall.py", line 485, in <module>

    installer.start()

  File "C:\Users\zayn5\Downloads\custom-install-module-new-gui\custominstall.py", line 378, in start

    cifinish_data[int(cia.tmd.title_id, 16)] = {'seed': (cia.contents[0].seed if cia.contents[0].flags.uses_seed else None)}

**Comment by ihaveamac** [comment]
This doesn't include the entire traceback. Please include the last line too which has an exception/error name.

**Comment by zayn5498** [comment]
Hi, theres no last line showing, i have downloaded cias from another website and it has worked fine thank you.

**Comment by zayn5498** [comment]
AttributeError: 'NCCHReader' object has no attribute 'seed' 
I have just seen the error not sure what it means?
