### ISSUE TITLE
CIA release for custom-install-finalize

### ISSUE THREAD

**Issue by MillaBasset** [ihaveamac/custom-install#35]
I use custom-install frequently so I just decided to create a CIA type thing for ci-finalize. Here's the CIA QR code:
![](https://cdn.discordapp.com/attachments/740992532078526487/752579483294236672/hoAAAAASUVORK5CYII.png)

To build yourself:
1. `git clone` the repository.
2. Change directories to the `finalize` directory.
3. Ensure devkitARM is installed, and run `make`.
4. Download [this package](https://cdn.discordapp.com/attachments/740992532078526487/752579289622511776/custom-install-finalize.7z) and extract everything (besides the elf, unless you don't have faith in your own compilation).
5. Make sure you have makerom and all the contents in the same directory, and run `makerom -f cia -rsf custom-install-finalize.rsf -target t -elf custom-install-finalize.elf -icon custom-install-finalize.smdh -banner custom-install-finalize.bnr`.

**Comment by ihaveamac** [comment]
Thanks but I'm probably not going to be making cia releases.
