### ISSUE TITLE
Error when fisnishing instalation

### ISSUE THREAD

**Issue by SFX-94** [ihaveamac/custom-install#38]
16:56:29 - Starting install...
16:56:29 - Finding path to install to...
16:56:29 - Reading C:\Users\Marla\Desktop\Games 2\Ishi-Sengokuden SADAME.cia
16:56:30 - Installing SADAME...
16:56:30 - Writing /title/00040000/00186c00/content/00000000.tmd...
16:56:30 - Writing /title/00040000/00186c00/content/00000000.app...
16:57:49 - Generating blank save at /title/00040000/00186c00/data/00000001.sav...
16:57:49 - Generating /title/00040000/00186c00/content/cmd/00000001.cmd
16:57:49 - Writing /title/00040000/00186c00/content/cmd/00000001.cmd
16:57:49 - Extracting Title Database...
16:57:50 - Host IO error: Os { code: 3, kind: NotFound, message: "O sistema nÃ£o pode encontrar o caminho especificado." }
16:57:50 - Error: IO(Os { code: 3, kind: NotFound, message: "O sistema nÃ£o pode encontrar o caminho especificado." })
16:57:50 - 
16:57:50 - Traceback (most recent call last):
16:57:50 -   File "ci-gui.py", line 401, in install
16:57:50 - TypeError: cannot unpack non-iterable bool object

**Comment by ihaveamac** [comment]
title.db doesn't exist, it needs to be initialized. Open FBI to create it. Then re-run custom-install, choose the same CIA, but check "Skip contents" so the game doesn't need to be fully re-installed.

**Comment by SFX-94** [comment]
> title.db doesn't exist, it needs to be initialized. Open FBI to create it. Then re-run custom-install, choose the same CIA, but check "Skip contents" so the game doesn't need to be fully re-installed.

I'm sorry. How do I create that on FBI? I'm rather new to the scene. My setup was fine but then I fucked up when tried to move everything to a bigger sd card.

**Comment by ihaveamac** [comment]
Opening FBI is enough, it creates the title.db on launch. Though if you said you tried to move to a larger SD card there might be a different issue with multiple id1 directories. Check inside "Nintendo 3DS" -> (id0), how many folders are here?

**Comment by SFX-94** [comment]
There's 2 numbered ones, then extdata, dbs and title. I'm having to reinstall everything for being incompetent and not researching enough.

**Comment by ihaveamac** [comment]
One of those folders has your old games and things. You should figure out which one is smaller and delete (or move it somewhere else).

**Comment by SFX-94** [comment]
I did a clean install. Figured it would have been less of a headache.

**Comment by ihaveamac** [comment]
The data is likely still there, so you should still delete or move the smaller id1 folder. Having two is going to cause confusion in the future regardless.

**Comment by SFX-94** [comment]
Now attempting to install a small game to see if everything works. Thanks for your assistance, man, I appreciate your patience,

**Comment by SFX-94** [comment]
I meant to say I deleted those on purpose to reinstall them. Formatted sd and everything.
