### ISSUE TITLE
Nintendo 3DS hashed folder name is different than the usual

### ISSUE THREAD

**Issue by ertaboy356b** [ihaveamac/custom-install#39]
After formatting my 2DS, the Nintendo 3DS folder generated a different folder than the usual one that this software is using. Can you please make this value editable via config file or something?

![image](https://user-images.githubusercontent.com/9444516/102306727-dae83b00-3f9d-11eb-8bb6-43b93da5aa0d.png)

**Comment by ihaveamac** [comment]
This hash is generated from movable.sed, so you need to re-dump this file after formatting.
