### ISSUE TITLE
Error with savefuse

### ISSUE THREAD

**Issue by Legarad** [ihaveamac/custom-install#4]
Extracting Title Database...
Traceback (most recent call last):
  File "custom-install.py", line 318, in <module>
    subprocess.run(save3ds_fuse_common_args + ['-x'])
  File "C:\Python3\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python3\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 216] Esta versión de %1 no es compatible con la versión de Wi
ndows que está ejecutando. Compruebe la información de sistema del equipo para c
onsultar si necesita una versión x86 (32 bits) o x64 (64 bits) del programa, y d
espués póngase en contacto con el editor del software

**Comment by evertonstz** [comment]
Are you on a 32bit system?

**Comment by Legarad** [comment]
Correct I still use the Windows 7 32bit operating system, I understand that 64-bit operating system requires a 4GB RAM and for that reason I have not updated.

**Comment by evertonstz** [comment]
> I understand that 64-bit operating system requires a 4GB RAM and for that reason I have not updated.

Not at all, you can run Windows 7 64bits with 2gb of ram, most linux distros will do fine even with 1gb. I have a Netbook runing PuppyLinux that has only 512mb. Anyways, you'll have three options to use this script:

- install a 64bits OS (that's recommended, 32bits is ancient and is being phased out);

- compile a [save3ds](https://github.com/wwylele/save3ds) 32bits binary and overrite the bundled binary inside custom-install/bin/win32/

- get someone with a 32 bit windows to compile it for you, that's gonna be hard to find.

**Comment by ihaveamac** [comment]
save3ds_fuse.exe will be replaced with a 32-bit build soon, since there is no benefit for it to be 64-bit.

**Comment by Legarad** [comment]
> > I understand that 64-bit operating system requires a 4GB RAM and for that reason I have not updated.
> 
> Not at all, you can run Windows 7 64bits with 2gb of ram, most linux distros will do fine even with 1gb. I have a Netbook runing PuppyLinux that has only 512mb. Anyways, you'll have 3 options to use this script:
> 
> * install a 64bits OS (that's recommended, 32bits is ancient and is being phased out);
> * compile a [save3ds](https://github.com/wwylele/save3ds) 32bits binary and overrite the bundled binary inside custom-install/bin/win32/
> * get someone with a 32 bit windows to compile it for you, that's gonna be hard to find.

Is compilation easy?

**Comment by ihaveamac** [comment]
Forgot to close this, the executable has been replaced with a 32-bit version a long time ago.
