### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by overarchiver** [ihaveamac/custom-install#41]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 110: illegal multibyte sequence

**Comment by ihaveamac** [comment]
Can you post the fill traceback? You can censor any sensitive details like usernames.

**Comment by overarchiver** [comment]
19:52:29 - custom-install 2.1b3 - https://github.com/ihaveamac/custom-install
19:52:29 - Ready.
19:52:29 - Note: boot9 was not auto-detected. Please choose it before adding any titles.
19:52:52 - Found movable.sed on SD card at E:/gm9\out\movable.sed
19:53:30 - Starting install...
19:53:30 - Finding path to install to...
19:53:30 - Extracting Title Database...
19:53:33 - Installing Mario & Luigi: Superstar… - 0004000000194b00...
19:53:34 - Writing /title/00040000/00194b00/content/00000000.tmd...
19:53:34 - Writing /title/00040000/00194b00/content/00000000.app...
19:54:05 - Writing /title/00040000/00194b00/content/00000001.app...
19:54:05 - Generating blank save at /title/00040000/00194b00/data/00000001.sav...
19:54:05 - Generating /title/00040000/00194b00/content/cmd/00000001.cmd
19:54:05 - Writing /title/00040000/00194b00/content/cmd/00000001.cmd
19:54:05 - Importing into Title Database...
19:54:06 - Traceback (most recent call last):
19:54:06 -   File "ci-gui.py", line 690, in install
19:54:06 -   File "Z:\Projects\custom-install\custominstall.py", line 606, in start
19:54:06 -   File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 495, in run
19:54:06 -   File "C:\Program Files (x86)\Python38-32\lib\subprocess.py", line 1015, in communicate
19:54:06 - UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 110: illegal multibyte sequence
