### ISSUE TITLE
An Error Occured During The Installation

### ISSUE THREAD

**Issue by skylartr** [ihaveamac/custom-install#45]
Please help
16:50:05 - Starting install...
16:50:05 - Finding path to install to...
16:50:05 - Traceback (most recent call last):
16:50:05 -   File "ci-gui.py", line 401, in install
16:50:05 -   File "custominstall.py", line 188, in start
16:50:05 -   File "custominstall.py", line 485, in get_sd_path
16:50:05 - FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/Nintendo 3DS\\ff084737d59d71f775c89e9728d26cd5'

**Comment by ZeroSkill1** [comment]
Looks like you're using the wrong `movable.sed` or the `Nintendo 3DS` folder doesn't exist on your SD Card.

**Comment by skylartr** [comment]
Thanks that helped. 👍
