### ISSUE TITLE
Offer on programm

### ISSUE THREAD

**Issue by BpyH64** [ihaveamac/custom-install#5]
1.The command line can be simplified.
custom-install.py --sd E: \ --cia file.cia
boot9.bin, movable.sed, seeddb.bin put next to custom-install.py and they will be processed automatically.

2.Each call to custom-install.py will check for cifinish.bin and update (supplement) it.

3.custom-install-finalize.3ds after completion removes cifinish.bin.

4.Util save3ds_fuse  rewrite to python3 version (save3ds_fuse.py)

**Comment by ihaveamac** [comment]
> 1.The command line can be simplified.
custom-install.py --sd E: \ --cia file.cia
boot9.bin, movable.sed, seeddb.bin put next to custom-install.py and they will be processed automatically.
>
> 2.Each call to custom-install.py will check for cifinish.bin and update (supplement) it.
>
> 3.custom-install-finalize.3ds after completion removes cifinish.bin.

This will be added eventually.

> 4.Util save3ds_fuse rewrite to python3 version (save3ds_fuse.py)

Someone else would have to do this, unfortunately I'm not interested in rewriting it myself.

**Comment by BpyH64** [comment]
Or code save3ds_fuse can inject in custom-install-finalize.3ds and in the file cifinish.bin write the size of the game.

**Comment by ihaveamac** [comment]
99556990457ded3d9f2f4b3522715c4032ce2fbc 2f0fc5d177d2423af5579b7b86442a3b56cc025f cifinish.bin is updated in-place and removed by custom-install-finalize

**Comment by ihaveamac** [comment]
Some of these will be moved to their own issues.
