### ISSUE TITLE
Suggest building optimized save3ds_fuse

### ISSUE THREAD

**Issue by Nemris** [ihaveamac/custom-install#58]
By default, `cargo build` produces a binary suited for debugging, which is considerably larger and, at times, slower than what is optimal.

I suggest recommending users to build the executable in release mode by using `cargo build --release`, which will then place the binary under `target/release/`.

**Comment by ihaveamac** [comment]
Binaries were updated in 68f6bfbb2eb54a086675ead4e0ea0309d295a18b to use `--release`, as well as provide a universal binary for Mac.

**Comment by ihaveamac** [comment]
README updated a1b3cb059e261c88178670f7300a05c0c5ae5a76
