### ISSUE TITLE
ci-gui.exe Error when launching.

### ISSUE THREAD

**Issue by FernTime** [ihaveamac/custom-install#59]
I have used the custom install app before and it has worked fine, but today i got this weird error when trying to open ci-gui.exe that i have no idea as to why it happens.
https://imgur.com/a/dE8OzxB
The first image was after a few tries, the second one is one of the first attempts at opening the executable, where a weird mess of text appears on the error message.
I've tried redownloading the app, running as admin and deactivating any antivirus software and nothing seems to work.
Sorry if this is not the correct place to put this up, i'm new to this stuff.

**Comment by ihaveamac** [comment]
This looks like corruption is happening somewhere but I'm not sure what. Try running chkdsk on whatever drive custom-install is being run from.

**Comment by FernTime** [comment]
Apologies for the late response, but yes, it was some sort of corruption. I tested the program on another computer and it seems to work perfectly. Just a few weeks ago i realized that i had a virus wrecking stuff up, so it could've been that.
Thanks for the reply anyway!
