### ISSUE TITLE
No --seeddb command line option.

### ISSUE THREAD

**Issue by Hellrespawn** [ihaveamac/custom-install#6]
Unlike what the readme says, there is no "--seeddb" option available.

**Comment by Mrye** [comment]
same problem

**Comment by ihaveamac** [comment]
Oops, I thought I added one. I should get on this soon.

**Comment by ninep9up** [comment]
> 
> 
> Oops, I thought I added one. I should get on this soon.

From the looks of it yet soon is not yet there.

**Comment by ihaveamac** [comment]
Things have been a bit slow lately but I've been getting back into maintaining these projects, so this should actually be added in the next few days.

**Comment by ihaveamac** [comment]
Oops, issues only close via commits on the default branch.
