### ISSUE TITLE
Can't install .cia games anymore

### ISSUE THREAD

**Issue by wrenchy-matt** [ihaveamac/custom-install#62]
I don't understand: the first time I installed games in CIA format it worked, but I wanted to do it a second time on the same SD card and it says that my ID was not found, but it IS my ID
![IMG_20220420_203614_903](https://user-images.githubusercontent.com/104130537/164507781-3754defb-6f0c-46cb-add4-dd9b7f70fd4b.jpg)
![IMG_20220420_203512_458](https://user-images.githubusercontent.com/104130537/164507785-97de399b-3133-455f-aa43-c11c3f17bfb1.jpg)
![IMG_20220420_203500_727](https://user-images.githubusercontent.com/104130537/164507788-5447341b-9388-4e79-94bb-8a0c85ee4021.jpg)

**Comment by ihaveamac** [comment]
SD root is incorrectly set to D:/gm9/out when it should just be D:

**Comment by wrenchy-matt** [comment]
Thank you very much !
