### ISSUE TITLE
The finalize.3dsx is missing GUI version

### ISSUE THREAD

**Issue by wyxls** [ihaveamac/custom-install#8]
I notice that the initial version finalize.3dsx is in the release page but there's no GUI version corresponding to the GUI-custom-install (or module-rewrite branch)

**Comment by ihaveamac** [comment]
Yeah I've been kind of busy with other things lately and haven't worked on my projects much. The GUI branch isn't finished yet so there is no release yet. custom-install-finalize in the module-rewrite branch is updated though so you should be able to build and use that.

**Comment by ihaveamac** [comment]
Here is the current custom-install-finalize for module-rewrite. Please tell me how it works. 
[custom-install-finalize.3dsx.zip](https://github.com/ihaveamac/custom-install/files/4002041/custom-install-finalize.3dsx.zip)

This project isn't abandoned by the way, I'll eventually get around to updating it.

**Comment by wyxls** [comment]
Thanks for replying. 

I'm a normal user with little command line experience and don't know how to build 3dsx from those main.c and makefile.

Anyway, I'll test the 3dsx and post the follow-up here

**Comment by wyxls** [comment]
> Here is the current custom-install-finalize for module-rewrite. Please tell me how it works.
> [custom-install-finalize.3dsx.zip](https://github.com/ihaveamac/custom-install/files/4002041/custom-install-finalize.3dsx.zip)
> 
> This project isn't abandoned by the way, I'll eventually get around to updating it.

Unfortunately, the module-rewrite 3dsx you provided seemed doesn't work. My New 3DSLL with v11.12.0-44U only got few "Finalizing 0004000e……Finalizing 000400" messages (only 8-bit characters) while running the new finalize.3dsx.

I tested the initial custom-install to install those same CIAs and got “0004000000ea5100……” like 16-bit characters.

**Comment by ihaveamac** [comment]
I see something that went wrong. The script created cifinish.bin incorrectly (putting the has_seed byte in the wrong place).

**Comment by ihaveamac** [comment]
The script and finalize application are fixed now in module-rewrite. cifinish version has been bumped to 3 to help reduce confusion with bad versions of cifinish version 2. custominstall.py also updates cifinish.bin in-place and will upgrade it from an older version.

**Comment by ihaveamac** [comment]
custom-install-finalize now supports all 3 versions. https://github.com/ihaveamac/custom-install/releases/tag/finalize-1.3
